apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitjgmdsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aitjgmdsb
  template:
    metadata:
      labels:
        app: aitjgmdsb
    spec:
      containers:
      - image: okteto.dev/aitjgmdsb:latest
        name: aitjgmdsb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "68ce79aa-c52b-4c50-914d-64d42259f6ca"
        - name: Vless_Path
          value: "/vlt44655"
        - name: Vmess_UUID
          value: "68ce79aa-c52b-4c50-914d-64d42259f6ca"
        - name: Vmess_Path
          value: "/vm66def46"
        - name: Share_Path
          value: "/v2link"
